### PR TITLE
Resolves issue #5 - Add new feature: Nodemailer based contact form

### LINKED ISSUE #5: feature: nodemailer based contact form
Hi!

Is there a need of having a contact form that directly sends message to your mailbox? I can implement that using nodemailer. You have to just provide alternate google account's developer access in your deployment platform's env variables.

### PR DESCRIPTION
**Pull request by HarshArora-1205**
**This PR resolve the issue -#5**
- #5 

- [x] Add new contact form
- [x] Implement API route to handle form submission
- [x] Configure google account credentials (for local testing. see .env.example)

To configure your mail credentials, setup google account app password [here](https://myaccount.google.com/u/0/apppasswords)

Test the code and share the feedback. Thoughts are welcomed. 😄

### CODE REVIEW

**Comment by HarshArora-1205** [comment]
Checking restyled error.

**Comment by HarshArora-1205** [comment]
Thanks for fixing linitng errors and merging code.

**Comment by HarshArora-1205** [comment]
Hi! are env variables set in vercel's settings?

**Comment by SandeepVashishtha** [comment]
@HarshArora-1205 Hi! Yes, I’ve set up the environment variables in Vercel's settings. However, after clicking the "Ping" button to send a message, it gets stuck on "Pinging" and the message is not sent.

**Comment by HarshArora-1205** [comment]
> @HarshArora-1205 Hi! Yes, I’ve set up the environment variables in Vercel's settings. However, after clicking the "Ping" button to send a message, it gets stuck on "Pinging" and the message is not sent.

Will look into this. Also is your key and env correct?

**Pull request merged**
